# Conformal Prediction Configuration
experiment_name: "friedman2_lightgbm_cqr_method"

# Paths
data:
  train_path: "/ssd_4TB/divake/CP_llm/friedman2_dataset/train_data.csv"
  validation_path: "/ssd_4TB/divake/CP_llm/friedman2_dataset/validation_data.csv"
  test_path: "/ssd_4TB/divake/CP_llm/friedman2_dataset/test_data.csv"
  model_path: "/ssd_4TB/divake/CP_llm/friedman2_rf_regression/random_forest_model.joblib"
  
# Conformal Prediction Parameters
conformal_prediction:
  # Method selection
  method: "cqr"
  alpha: 0.1  # Significance level (1-alpha = coverage level)
  
  # Scoring function for CQR
  scoring_function: "quantile_residual"
  
  # CQR specific parameters
  low_quantile: 0.05  # Lower quantile level (alpha/2)
  high_quantile: 0.95  # Upper quantile level (1-alpha/2)

# Quantile Model Parameters for CQR
quantile_model_type: "lightgbm"  # Using LightGBM for quantile regression
lightgbm_params:
  objective: "quantile"
  metric: "quantile"
  verbosity: -1
  boosting_type: "gbdt"
  num_leaves: 31
  learning_rate: 0.05
  feature_fraction: 0.9
  bagging_fraction: 0.8
  bagging_freq: 5
  n_estimators: 500
  random_state: 42

# If true, will attempt to load existing quantile models rather than training new ones
use_existing_quantile_models: false
  
# Evaluation Metrics
evaluation:
  metrics:
    - "theoretical_coverage"
    - "empirical_coverage"
    - "interval_width"
    - "training_cost"
    - "evaluation_cost"
  
# Output
output:
  results_dir: "/ssd_4TB/divake/CP_llm/mapie/results/lightgbm_cqr_method"
  log_level: "INFO"
