# Conformal Prediction Configuration
experiment_name: "friedman2_cqr_method"

# Paths
data:
  train_path: "/ssd_4TB/divake/CP_llm/friedman2_dataset/train_data.csv"
  validation_path: "/ssd_4TB/divake/CP_llm/friedman2_dataset/validation_data.csv"
  test_path: "/ssd_4TB/divake/CP_llm/friedman2_dataset/test_data.csv"
  model_path: "/ssd_4TB/divake/CP_llm/friedman2_rf_regression/random_forest_model.joblib"
  
# Conformal Prediction Parameters
conformal_prediction:
  # Main method selection
  method: "cqr"  # Using CQR method instead of split
  alpha: 0.1  # Significance level (1-alpha = coverage level)
  
  # Scoring function for CQR will be automatically set
  scoring_function: "quantile_residual"
  
  # CQR specific parameters
  low_quantile: 0.05  # Lower quantile level (alpha/2)
  high_quantile: 0.95  # Upper quantile level (1-alpha/2)

# Quantile Model Parameters for CQR
quantile_model_type: "quantile_regressor"  # Options: quantile_regressor, gradient_boosting

# If true, will attempt to load existing quantile models rather than training new ones
use_existing_quantile_models: false
  
# Evaluation Metrics
evaluation:
  metrics:
    - "theoretical_coverage"
    - "empirical_coverage"
    - "interval_width"
    - "training_cost"
    - "evaluation_cost"
  
# Output
output:
  results_dir: "/ssd_4TB/divake/CP_llm/mapie/results/cqr_method"
  log_level: "INFO"
